apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-t1be
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-t1be
    app.kubernetes.io/part-of: tkrw-pr712-0075-0009-app
  name: devfile-sample-t1be
spec:
  ports:
  - name: http-3001
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: nodejs-app
    app.kubernetes.io/instance: devfile-sample-t1be
status:
  loadBalancer: {}
